### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by ltcszk** [pragmatrix/BuildOnSave#47] opened 2017-05-10 01:27 UTC
---------- BuildOnSave CRASHED, please report to https://www.github.com/pragmatrix/BuildOnSave/issues
System.InvalidOperationException: Sequence contains no elements
   在 System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   在 BuildOnSave.BackgroundBuild2.printIntro(BuildRequest request)
   在 BuildOnSave.BackgroundBuild2.buildCore(BuildRequest request, CancellationToken cancellation)
   在 BuildOnSave.BackgroundBuild2.build(BuildRequest request, CancellationToken cancellation, Action`1 onCompleted)

**Comment by pragmatrix** [comment] 2017-05-10 09:57
Hello Itcszk, thank you for the bug report. 

This is probably a duplicate of #44, which should be fixed in the master branch. I'll make a new release soon I am back from my vacation in about two weeks.

**Comment by pragmatrix** [comment] 2017-05-22 18:24
I've published a new pre-release, which should fix the problem you've described: https://github.com/pragmatrix/BuildOnSave/releases

**Closed** 2017-09-16 15:42 UTC
Labels: bug
